#! python


def build(ctx):

    ctx(
        rule="pdftotext -layout -enc 'UTF-8' ${SRC} ${TGT}",
        source=ctx.path_to(ctx, "IN_DATA", "HandbuchDtAGs_1925_1_Band.pdf"),
        target=ctx.path_to(ctx, "OUT_DATA", "HandbuchDtAGs_1925_1_Band.txt")
    )

    # # Illustrate simple use of run_py_script
    # ctx(
    #     features='run_py_script',
    #     source='get_simulation_draws.py',
    #     target=ctx.path_to(ctx, 'OUT_DATA', 'initial_locations.csv'),
    #     name='get_simulation_draws'
    # )
